# Generated by Django 6.0 on 2025-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selosverdes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selosverdes',
            name='file_name_logo',
            field=models.ImageField(blank=True, null=True, upload_to='selosverdes/', verbose_name='Logo do Selo (upload)'),
        ),
    ]
