# Generated by Django 6.0 on 2025-12-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelosVerdes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Selo Verde')),
                ('issuing_body', models.CharField(blank=True, max_length=200, null=True, verbose_name='Órgão Emissor')),
                ('description', models.TextField(verbose_name='Descrição do Selo')),
                ('official_link', models.URLField(blank=True, null=True, verbose_name='Link Oficial')),
                ('file_name_logo', models.ImageField(blank=True, null=True, upload_to='selos_logos/', verbose_name='Logo do Selo (upload)')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Selo Verde',
                'verbose_name_plural': 'Selos Verdes',
                'ordering': ['name'],
            },
        ),
    ]
