# Generated by Django 6.0 on 2025-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selosverdes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoresRurais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=300, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('email_adress', models.EmailField(max_length=254, unique=True, verbose_name='Endereço Eletrônico')),
                ('adress', models.TextField(verbose_name='Endereço Completo')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Telefone')),
                ('certificate_upload', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Cópia do(s) Certificado(s)')),
                ('selos', models.ManyToManyField(blank=True, to='selosverdes.selosverdes', verbose_name='Selos Verdes')),
            ],
            options={
                'verbose_name': 'Produtor Rural',
                'verbose_name_plural': 'Produtores Rurais',
                'ordering': ['full_name'],
            },
        ),
    ]
