# Generated by Django 6.0 on 2025-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoresrurais',
            name='verificate',
            field=models.BooleanField(default=False, help_text='Marque após a verificação dos dados e certificados do produtor.', verbose_name='Status de verificação'),
        ),
    ]
