# Generated by Django 6.0 on 2025-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0002_produtoresrurais_verificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoresrurais',
            name='certificate_upload',
            field=models.FileField(blank=True, null=True, upload_to='produtores/', verbose_name='Cópia do(s) Certificado(s)'),
        ),
    ]
