# Generated by Django 6.0 on 2026-01-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0003_alter_produtoresrurais_certificate_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoresrurais',
            name='city',
            field=models.CharField(default='Não informada', max_length=100, verbose_name='Município'),
        ),
    ]
