# Generated by Django 6.0 on 2026-01-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0004_produtoresrurais_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoresrurais',
            name='neighborhood',
            field=models.CharField(default='Não Informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='produtoresrurais',
            name='city',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Município'),
        ),
    ]
