# Generated by Django 6.0 on 2026-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0005_produtoresrurais_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoresrurais',
            name='neighborhood',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Bairro'),
        ),
    ]
