# Generated by Django 6.0 on 2026-01-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0006_alter_produtoresrurais_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoresrurais',
            name='costume_name',
            field=models.CharField(blank=True, default='Pessoa Física', max_length=300, null='True', verbose_name='Nome Fantasia da empresa'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='produtoresrurais',
            name='employment_name',
            field=models.CharField(blank=True, default='Pessoa Física', max_length=300, null='True', verbose_name='Nome da empresa'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='produtoresrurais',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='Nome completo do responsável'),
        ),
    ]
