# Generated by Django 6.0 on 2026-01-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0007_produtoresrurais_costume_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoresrurais',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='produtoresrurais',
            name='state',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Estado'),
        ),
    ]
