# Generated by Django 6.0 on 2026-01-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0008_remove_produtoresrurais_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoresrurais',
            name='adress',
            field=models.CharField(verbose_name='Logradouro com número'),
        ),
        migrations.AlterField(
            model_name='produtoresrurais',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='produtoresrurais',
            name='costume_name',
            field=models.CharField(blank=True, default='Pessoa Física', max_length=300, null=True, verbose_name='Nome Fantasia da empresa'),
        ),
        migrations.AlterField(
            model_name='produtoresrurais',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='produtoresrurais',
            name='employment_name',
            field=models.CharField(blank=True, default='Pessoa Física', max_length=300, null=True, verbose_name='Nome da empresa'),
        ),
    ]
