# Generated by Django 6.0 on 2026-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0009_alter_produtoresrurais_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoresrurais',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
