# Generated by Django 6.0 on 2026-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0011_produtoresrurais_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoresrurais',
            name='summary_prod',
            field=models.TextField(blank=True, default='Não descrito', max_length=500, null=True, verbose_name='Descrição breve do que é produzido'),
        ),
    ]
