# Generated by Django 6.0 on 2026-01-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0012_produtoresrurais_summary_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoresrurais',
            name='password',
        ),
    ]
